---
- hosts: all
  become: yes
  vars:
    mysql_user: "{{ mysql_user }}"  # MySQL root user from Jenkins credentials
    mysql_password: "{{ mysql_root_password }}"  # MySQL root password from Jenkins credentials
    replication_user: "{{ replication_user }}"  # Replication user from Jenkins credentials
    replication_password: "{{ replication_password }}"  # Replication password from Jenkins credentials
    ansible_python_interpreter: /usr/bin/python3  # Ensures compatibility with Amazon Linux

  tasks:
    - name: Install MySQL Yum repository
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
        state: present

    - name: Install MySQL
      yum:
        name: mysql-community-server
        state: present
      tags: mysql

    - name: Start MySQL service
      service:
        name: mysqld
        state: started
        enabled: true
      tags: mysql_start

    - name: Get MySQL default root password
      command: /usr/bin/mysql_secure_installation --set-root-pass "{{ mysql_password }}"
      register: mysql_root_pass
      ignore_errors: yes  # Ignore errors in case mysql_secure_installation runs
      tags: mysql_secure

    - name: Wait for MySQL to be ready
      wait_for:
        port: 3306
        delay: 10
        timeout: 60
      tags: mysql_wait

    - name: Configure MySQL server ID and binary log on Master
      when: "'master' in group_names"
      blockinfile:
        path: /etc/my.cnf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          server-id=1
          log-bin=mysql-bin
      notify: restart mysql
      tags: mysql_config

    - name: Configure MySQL server ID on Slave
      when: "'slave' in group_names"
      blockinfile:
        path: /etc/my.cnf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          server-id=2
      notify: restart mysql
      tags: mysql_config

    - name: Restart MySQL to apply configuration changes
      service:
        name: mysqld
        state: restarted
      tags: mysql_restart

    - name: Create replication user on Master
      when: "'master' in group_names"
      mysql_user:
        name: "{{ replication_user }}"
        password: "{{ replication_password }}"
        host: '%'
        priv: "*.*:REPLICATION SLAVE"
        state: present
      tags: mysql_replication_user

    - name: Get Master status (log file and position)
      when: "'master' in group_names"
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: "SHOW MASTER STATUS;"
      register: master_status
      tags: mysql_master_status

    - name: Set Master log file and position on Slave
      when: "'slave' in group_names"
      mysql_replication:
        mode: "slave"
        master_host: "{{ hostvars[groups['master'][0]].ansible_host }}"
        master_user: "{{ replication_user }}"
        master_password: "{{ replication_password }}"
        master_log_file: "{{ hostvars[groups['master'][0]].master_status.query_result[0].File }}"
        master_log_pos: "{{ hostvars[groups['master'][0]].master_status.query_result[0].Position }}"
      tags: mysql_slave_config

    - name: Start replication on Slave
      when: "'slave' in group_names"
      mysql_replication:
        mode: start
      tags: mysql_slave_start

  handlers:
    - name: restart mysql
      service:
        name: mysqld
        state: restarted
